python -m pyserini.encode input \
  --corpus /content/temp/data/full_wiki_segments.jsonl \
  --fields text \
  --delimiter "\n" \
  --shard-id 0 \
  --shard-num 2 output \
  --embeddings path/to/output/dir-0 \
  --to-faiss encoder \
  --encoder castorini/tct_colbert-v2-hnp-msmarco \
  --fields text \
  --batch 128 \
  --fp16
