python3 train_cqg.py \
    --model_name_or_path t5-small \
    --n_contexts 2 \
    --output_dir ./fidcqg \
    --train_file data/train_cqg_v0.sample.jsonl \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --max_length 256 \
    --max_steps 100 \
    --save_steps 50\
    --eval_steps 25 \
    --do_train true \
    --do_eval false \
    --dataloader_num_workers 0 \
    --dataloader_pin_memory false \
    --remove_unused_columns false
